# Generated by Django 5.1 on 2024-08-29 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrashCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("volume", models.FloatField()),
                (
                    "bag_size",
                    models.CharField(
                        choices=[
                            ("10L", "10 Liters"),
                            ("20L", "20 Liters"),
                            ("30L", "30 Liters"),
                            ("40L", "40 Liters"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_collected", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
