# Generated by Django 5.1 on 2024-09-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashcollection", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trashcollection",
            old_name="date_collected",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="trashcollection",
            name="bag_size",
        ),
        migrations.RemoveField(
            model_name="trashcollection",
            name="location",
        ),
        migrations.RemoveField(
            model_name="trashcollection",
            name="volume",
        ),
        migrations.AddField(
            model_name="trashcollection",
            name="bags_collected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trashcollection",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name="trashcollection",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
