# Generated by Django 5.1 on 2024-09-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_location_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
    ]
