# Generated by Django 5.1 on 2024-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="default_profile_pic.png", upload_to="profile_pics/"
            ),
        ),
    ]
